{% set build = 0 %}
{% set version = "2022.06.08" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: {{ build }}

requirements:
  build:
    - {{ moose_python }}
    - openssl
    - setuptools
  run:
    - numpy
    - matplotlib
    - pandas
    - pyyaml
    - pybtex
    - mock
    - lxml
    - scikit-image
    - sympy
    - deepdiff
    - beautifulsoup4
    - pylatexenc
    - jinja2
    - mako
    - livereload
    - yaml
    - python
    - openssl
    - setuptools

test:
  imports:
    - numpy
    - matplotlib
    - pandas
    - livereload
    - yaml
    - bs4
    - pybtex
    - mock
    - lxml
    - skimage
    - sympy
    - pylatexenc
    - jinja2
    - deepdiff

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-tools) acts as a top-level module designed to provide all
    dependencies required in order to run Peacock and MOOSE Documentation.

extra:
  recipe-maintainers:
    - milljm
