{% set build = 0 %}
{% set version = "2020.08.11" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: .

build:
  number: {{ build }}
  skip: true                 # [win]

requirements:
  build:
    - python {{ python }}
    - vtk {{ vtk }}
  run:
    - numpy
    - pyqt
    - matplotlib
    - pandas
    - livereload
    - yaml
    - pyyaml
    - beautifulsoup4
    - pybtex
    - mock
    - lxml
    - scikit-image
    - vtk {{ vtk }}
    - pylatexenc
    - jinja2
    - mako
    - python {{ python }}

test:
  imports:
    - vtk

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'This superficial module (moose-tools) acts as a top-level module designed to provide all dependencies required in order to run Peacock and MOOSE Documentation.'

extra:
  recipe-maintainers:
    - milljm
