CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

libllvm:
  - 9.0.1 ha1b3eb9_0

libclang:
  - 9.0.1 default_hf57f61e_0

compilerrt:
  - 9.0.1 h6a512c6_0

compilerrtosx:
  - 9.0.1 h6a512c6_0

clangxx:
  - 9.0.1 default_hf57f61e_0

clangosx:
  - 9.0.1 h05bbb7f_0

clangxxosx:
  - 9.0.1 h05bbb7f_0

clang:
  - 9.0.1 default_hf57f61e_0

llvmopenmp:
  - 10.0.1 h28b9765_0

osxfortran:
  - 9.3.0 h268312c_9

gcc:
  - 9.3.0 h7247604_29

gxx:
  - 9.3.0 ha9dd585_28

fortran:
  - 9.3.0 ha9dd585_28

gccimpl:
  - 9.3.0 hda68d29_13

libcxx:
  - 10.0.1 h5f48129_0

moose_compilers:
  - 2020.10.07
