moose_libgfortran:
  - libgfortran-ng 13.2.0 h69a702a_3                        # [linux]
  - libgfortran 5.0.0 13_2_0_h97931a8_1                     # [not arm64 and osx]
  - libgfortran 5.0.0 13_2_0_hd922786_1                     # [arm64]

moose_libgfortran5:
  - libgfortran5 13.2.0 ha4646dd_3                          # [linux]
  - libgfortran5 13.2.0 h2873a65_1                          # [not arm64 and osx]
  - libgfortran5 13.2.0 hf226fd6_1                          # [arm64]

moose_ld64:                                                 # [osx]
  - ld64 609                                                # [not arm64 and osx]
  - ld64_osx-arm64 609                                      # [arm64]

### Paraview (peacock) constraints/oddities, especially libclang
moose_clangcc:                                              # [osx]
  - clang 15.0.7 hac416ee_4                                 # [not arm64 and osx]
  - clang 15.0.7 haab561b_4                                 # [arm64]

moose_clangxx:                                              # [osx]
  - clangxx 15.0.7 default_h6b1ee41_4                       # [not arm64 and osx]
  - clangxx 15.0.7 default_h5c94ee4_4                       # [arm64]

moose_krb5:
  - krb5 1.21.2 h659d440_0                                  # [linux]
  - krb5 1.21.2 hb884880_0                                  # [not arm64 and osx]
  - krb5 1.21.2 h92f50d5_0                                  # [arm64]

moose_icu:
  - icu 73.2 hf5e326d_0                                     # [not arm64 and osx]
  - icu 73.2 h59595ed_0                                     # [linux]
  - icu 73.2 hc8870d7_0                                     # [arm64]

moose_libclang:
  - libclang 15.0.7 default_hb11cfb5_4                      # [linux]
  - libclang 15.0.7 default_h6b1ee41_4                      # [not arm64 and osx]
  - libclang 15.0.7 default_hd209bcb_4                      # [arm64]

moose_libclang13:
  - libclang13 15.0.7 default_ha2b6cf4_4                    # [linux]
  - libclang13 15.0.7 default_h89cd682_4                    # [not arm64 and osx]
  - libclang13 15.0.7 default_ha49e599_4                    # [arm64]

### End Paraview constraints

mpi:
  - moose-mpich

#### Support Libraries
moose_libxt:                                                # [linux]
  - libxt-devel-cos7-x86_64 1.1.5 h9b0a68f_1105             # [linux]

moose_libsm:                                                # [linux]
  - libsm-devel-cos7-x86_64 1.2.2 h9b0a68f_1105             # [linux]

moose_libx11:                                               # [linux]
  - libx11-devel-cos7-x86_64 1.6.7 h9b0a68f_1105            # [linux]

moose_libice:                                               # [linux]
  - libice-devel-cos7-x86_64 1.0.9 h9b0a68f_1105            # [linux]

moose_libxext:                                              # [linux]
  - libxext-devel-cos7-x86_64 1.3.3 h9b0a68f_1105           # [linux]

moose_mesa_libgl:                                           # [linux]
  - mesa-libgl-devel-cos7-x86_64 18.3.4 h9b0a68f_1105       # [linux]

moose_xorg_x11:                                             # [linux]
  - xorg-x11-proto-devel-cos7-x86_64 2018.4 h9b0a68f_1105   # [linux]

moose_libglu:                                               # [linux]
  - libglu 9.0.0                                            # [linux]

moose_mesalib:                                              # [linux]
  - mesalib 23.3.2 h6b56f8e_0                               # [linux]

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.15.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
