moose_libxt:                                                # [linux]
  - libxt-devel-cos7-x86_64 1.1.5                           # [linux]

moose_libsm:                                                # [linux]
  - libsm-devel-cos7-x86_64 1.2.2                           # [linux]

moose_libx11:                                               # [linux]
  - libx11-devel-cos7-x86_64 1.6.7                          # [linux]

moose_libice:                                               # [linux]
  - libice-devel-cos7-x86_64 1.0.9                          # [linux]

moose_libxext:                                              # [linux]
  - libxext-devel-cos7-x86_64 1.3.3                         # [linux]

moose_mesa_libgl:                                           # [linux]
  - mesa-libgl-devel-cos7-x86_64 18.3.4                     # [linux]

moose_xorg_x11:                                             # [linux]
  - xorg-x11-proto-devel-cos7-x86_64 2018.4                 # [linux]

moose_libglu:                                               # [linux]
  - libglu 9.0.0 hf484d3e_1000                              # [linux]

moose_mesalib:                                              # [linux]
  - mesalib 18.3.1 h590aaf7_0                               # [linux]

#### Compilers
base_mpich:
  - mpich 4.0.1 h846660c_100                                # [linux]
  - mpich 4.0.1 hd33e60e_100                                # [not arm64 and osx]
  - mpich 4.0.1 hd4b5bf3_100                                # [arm64]

base_mpicc:
  - mpich-mpicc 4.0.1 hb600da9_100                          # [linux]
  - mpich-mpicc 4.0.1 h4fd26ce_100                          # [not arm64 and osx]
  - mpich-mpicc 4.0.1 haad7f49_100                          # [arm64]

base_mpicxx:
  - mpich-mpicxx 4.0.1 h166bdaf_100                         # [linux]
  - mpich-mpicxx 4.0.1 h5eb16cf_100                         # [not arm64 and osx]
  - mpich-mpicxx 4.0.1 h1c322ee_100                         # [arm64]

base_mpifort:
  - mpich-mpifort 4.0.1 h924138e_100                        # [linux]
  - mpich-mpifort 4.0.1 hbb4e6a2_100                        # [not arm64 and osx]
  - mpich-mpifort 4.0.1 h3e96240_100                        # [arm64]

moose_ld64:                                                 # [osx]
  - ld64 609 h4dfd969_10                                    # [not arm64 and osx]
  - ld64_osx-arm64 609 h7c97014_10                          # [arm64]

moose_hdf5:
  - hdf5 1.12.1 mpi_mpich_hfd824e9_4                        # [not arm64 and osx]
  - hdf5 1.12.1 mpi_mpich_h08b82f9_4                        # [linux]
  - hdf5 1.12.1 mpi_mpich_hfc22502_3                        # [arm64]

mpi:
  - moose-mpich

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.12.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
