{% set build = 8 %}
{% set strbuild = "build_" + build|string %}
{% set version = "3.3.2" %}

package:
  name: moose-mpich
  version: {{ version }}

source:
  fn: mpich-{{ version }}.tar.gz
  url: https://www.mpich.org/static/downloads/{{ version }}/mpich-{{ version }}.tar.gz
  sha256: 4bfaf8837a54771d3e4922c84071ef80ffebddbb6971a006038d91ee7ef959b9

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('moose-mpich', max_pin='x.x') }}

requirements:
  build:
    - {{ cc_compiler }}
    - {{ cxx_compiler }}
    - {{ fortran_compiler }}
    - {{ moose_libcxx }}
    - {{ moose_openmp }}        # [osx]
    - {{ moose_llvm_tools }}    # [osx]
    - {{ moose_ld64 }}          # [osx]
    - {{ moose_cctools }}       # [osx]
    - autoconf                  # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - make                      # [unix]
    - gnuconfig                 # [arm64]
  host: []
  run:
    - {{ cc_compiler }}
    - {{ cxx_compiler }}
    - {{ fortran_compiler }}
    - {{ moose_libcxx }}
    - {{ moose_openmp }}        # [osx]
    - {{ moose_llvm_tools }}    # [osx]
    - {{ moose_ld64 }}          # [osx]
    - {{ moose_cctools }}       # [osx]
    - autoconf                  # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - make                      # [unix]
    - mpi 1.0 mpich
  test:
    commands:
      - echo "It works!"

about:
  home: http://www.mpich.org/
  license: MPICH
  license_file: COPYRIGHT
  license_family: Other
  summary: 'A high performance widely portable implementation of the MPI standard.'
  description: |
    MPICH is a high performance and widely portable implementation of the
    Message Passing Interface (MPI) standard.
  doc_url: http://www.mpich.org/documentation/guides
  dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page

extra:
  recipe-maintainers:
    - milljm
