{% set build = 8 %}
{% set strbuild = "build_" + build|string %}
{% set version = "3.3.2" %}

package:
  name: moose-mpich
  version: {{ version }}

source:
  fn: mpich-{{ version }}.tar.gz
  url: https://www.mpich.org/static/downloads/{{ version }}/mpich-{{ version }}.tar.gz
  sha256: 4bfaf8837a54771d3e4922c84071ef80ffebddbb6971a006038d91ee7ef959b9

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('moose-mpich', max_pin='x.x') }}

requirements:
  build:
    - gcc_linux-64 {{ moose_gcc }}                    # [linux]
    - gxx_linux-64 {{ moose_gxx }}                    # [linux]
    - gfortran_linux-64 {{ moose_fortran }}           # [linux]
    - gcc_impl_linux-64 {{ moose_gccimpl }}           # [linux]
    - clang {{ moose_clang }}                         # [osx]
    - clang_osx-64 {{ moose_clangosx }}               # [osx]
    - clang_osx-arm64 {{ moose_clangosx_arm }}        # [arm64]
    - clangxx {{ moose_clangxx }}                     # [osx]
    - clangxx_osx-64 {{ moose_clangxxosx }}           # [osx]
    - clangxx_osx-arm64 {{ moose_clangxxosx_arm  }}   # [arm64]
    - compiler-rt {{ moose_compilerrt }}              # [osx]
    - compiler-rt_osx-64 {{ moose_compilerrtosx }}    # [not arm64 and osx]
    - compiler-rt_osx-arm64 {{ moose_compilerrtosx }} # [arm64]
    - libllvm11 {{ moose_libllvm11 }}                 # [not arm64 and osx]
    - libllvm12 {{ moose_libllvm12 }}                 # [arm64]
    - clang-tools                                     # [osx]
    - llvm-openmp {{ moose_llvmopenmp }}              # [osx]
    - gfortran_osx-64 {{ moose_osxfortran }}          # [not arm64 and osx]
    - gfortran_osx-arm64 {{ moose_osxfortran }}       # [arm64]
    - libclang {{ moose_libclang }}                   # [osx]
    - libcxx {{ moose_libcxx }}                       # [osx]
    - make                                            # [unix]
    - autoconf                                        # [unix]
    - automake                                        # [unix]
    - libtool                                         # [unix]
    - gnuconfig                                       # [arm64]
  host: []
  run:
    - gcc_linux-64 {{ moose_gcc }}                    # [linux]
    - gxx_linux-64 {{ moose_gxx }}                    # [linux]
    - gfortran_linux-64 {{ moose_fortran }}           # [linux]
    - gcc_impl_linux-64 {{ moose_gccimpl }}           # [linux]
    - clang {{ moose_clang }}                         # [osx]
    - clang_osx-64 {{ moose_clangosx }}               # [osx]
    - clang_osx-arm64 {{ moose_clangosx_arm }}        # [arm64]
    - clangxx {{ moose_clangxx }}                     # [osx]
    - clangxx_osx-64 {{ moose_clangxxosx }}           # [osx]
    - clangxx_osx-arm64 {{ moose_clangxxosx_arm  }}   # [arm64
    - compiler-rt {{ moose_compilerrt }}              # [osx]
    - compiler-rt_osx-64 {{ moose_compilerrtosx }}    # [not arm64 and osx]
    - compiler-rt_osx-arm64 {{ moose_compilerrtosx }} # [arm64]
    - libllvm11 {{ moose_libllvm11 }}                 # [not arm64 and osx]
    - libllvm12 {{ moose_libllvm12 }}                 # [arm64]
    - clang-tools                                     # [osx]
    - llvm-openmp {{ moose_llvmopenmp }}              # [osx]
    - gfortran_osx-64 {{ moose_osxfortran }}          # [not arm64 and osx]
    - gfortran_osx-arm64 {{ moose_osxfortran }}       # [arm64]
    - libclang {{ moose_libclang }}                   # [osx]
    - libcxx {{ moose_libcxx }}                       # [osx]
    - mpi 1.0 mpich
  test:
    commands:
      - echo "It works!"

about:
  home: http://www.mpich.org/
  license: MPICH
  license_file: COPYRIGHT
  license_family: Other
  summary: 'A high performance widely portable implementation of the MPI standard.'
  description: |
    MPICH is a high performance and widely portable implementation of the
    Message Passing Interface (MPI) standard.
  doc_url: http://www.mpich.org/documentation/guides
  dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page

extra:
  recipe-maintainers:
    - milljm
