{% set version = "2024.01.15" %}

package:
  name: moose-pyhit
  version: {{ version }}

source:
  - path: ../../python/moosetree
    folder: pyhit
  - path: ../../framework/contrib/hit
    folder: src

build:
  number: 0
  string: build_0
  skip: true           # [win]
  noarch: python
  pin_depends: record

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ moose_wasp }}

  run:
    - {{ moose_wasp }}
    - setuptools

test:
  imports:
    - pyhit

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'HIT Parser'

extra:
  recipe-maintainers:
    - milljm
