#!/bin/bash
#PBS -N <JOB_NAME>
#PBS -l select=<NODES>:ncpus=<MPI_PROCS>
#PBS -l walltime=<WALLTIME>
<PBS_PROJECT>
<PBS_QUEUE>
#PBS -j oe
#PBS -o <OUTPUT>
#PBS -l place=free
<PRE_COMMAND>
JOB_NUM=${PBS_JOBID%\.*}

export MV2_ENABLE_AFFINITY=0
export MOOSE_COMMAND="cd <WORKING_DIR>; <COMMAND>"

if [ -n "<USE_APPTAINER>" ]; then
    module load use.moose
    module load moosetainer
else
    eval ${MOOSE_COMMAND}
fi
