mpi:
  - mpich
  - openmpi

mpi_version:
  - 4.1.2
  - 4.1.6

zip_keys:
  - mpi
  - mpi_version

moose_libgfortran5:
  - libgfortran5 13.2.0 ha4646dd_3                          # [linux]
  - libgfortran5 13.2.0 h2873a65_3                          # [not arm64 and osx]
  - libgfortran5 13.2.0 hf226fd6_3                          # [arm64]

moose_clangcc:                                              # [osx]
  - clang 15.0.7 hac416ee_4                                 # [not arm64 and osx]
  - clang 15.0.7 haab561b_4                                 # [arm64]

moose_clangxx:                                              # [osx]
  - clangxx 15.0.7 default_h6b1ee41_4                       # [not arm64 and osx]
  - clangxx 15.0.7 default_h5c94ee4_4                       # [arm64]

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.15.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
