# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   petsc/*
#   libmesh-vtk/*
#   peacock/*
#
# As well as any directions pertaining to modifying those files.
# ALSO: Follow the directions in scripts/tests/versioner_hashes.yaml
{% set version = "2024.02.14" %}

package:
  name: moose-mpi
  version: {{ version }}

source:
  - path: .

build:
  number: 0
  string: {{ mpi }}
  pin_depends: strict
  script_env:
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE

requirements:
  build:
    - {{ mpi }}
    - {{ mpi }}-mpicc {{ mpi_version }}
    - {{ mpi }}-mpicxx {{ mpi_version }}
    - {{ mpi }}-mpifort {{ mpi_version }}
    - {{ moose_libgfortran5 }}
    - {{ moose_clangcc }}                     # [osx]
    - {{ moose_clangxx }}                     # [osx]
    - hdf5=1.14.3=mpi_{{ mpi }}_*

  run:
    - {{ mpi }}
    - {{ mpi }}-mpicc {{ mpi_version }}
    - {{ mpi }}-mpicxx {{ mpi_version }}
    - {{ mpi }}-mpifort {{ mpi_version }}
    - {{ moose_libgfortran5 }}
    - {{ moose_clangcc }}                     # [osx]
    - {{ moose_clangxx }}                     # [osx]
    - hdf5=1.14.3=mpi_{{ mpi }}_*
    - automake 1.16.5
    - bison 3.4
    - zfp 0.5.5
    - autoconf
    - libtool
    - cmake
    - make
    - m4

  run_constrained:
    - python <{{3.12}}

test:
  commands:
    - test -f $PREFIX/etc/conda/activate.d/activate_moose-mpi.sh

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'A top-level package designed to control environment variables related to conda-forge provided MPICH'
  description: |
    MPICH is a high performance and widely portable implementation of the
    Message Passing Interface (MPI) standard.
  doc_url: http://www.mpich.org/documentation/guides
  dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
