mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2024.01.23 mpich_0
  - moose-libmesh 2024.01.23 openmpi_0

moose_wasp:
  - moose-wasp 2023.11.29

moose_tools:
  - moose-tools 2024.02.14

moose_peacock:
  - moose-peacock 2024.02.14

zip_keys:
  - mpi
  - moose_libmesh
