mpi:
  - mpich
  - openmpi

variant:
  - peacock
  - torch

moose_pytorch:
  - pytorch 2.1

moose_pytorch_cuda:                                     # [linux]
  - pytorch-cuda 12.1                                   # [linux]

moose_libmesh:
  - moose-libmesh 2024.05.05 mpich_1
  - moose-libmesh 2024.05.05 openmpi_1

moose_wasp:
  - moose-wasp 2024.05.08

moose_tools:
  - moose-tools 2024.07.17

zip_keys:
  - mpi
  - moose_libmesh
