mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2024.05.05 mpich_2
  - moose-libmesh 2024.05.05 openmpi_2

moose_wasp:
  - moose-wasp 2024.05.08

moose_tools:
  - moose-tools 2024.07.10

moose_peacock:
  - moose-peacock 2024.07.10

zip_keys:
  - mpi
  - moose_libmesh
