mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2024.04.08 mpich_1
  - moose-libmesh 2024.04.08 openmpi_1

moose_wasp:
  - moose-wasp 2024.04.23

moose_tools:
  - moose-tools 2024.05.02

moose_peacock:
  - moose-peacock 2024.04.17

zip_keys:
  - mpi
  - moose_libmesh
